"""initial_schema

Revision ID: 0001_initial_schema
Revises: None
Create Date: 2026-09-26 00:58:01.090286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001_initial_schema'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cancers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('canonical_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('anatomical_site', sa.String(length=128), nullable=True),
    sa.Column('parent_cancer_id', sa.String(length=36), nullable=True),
    sa.Column('taxonomy_codes', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_cancer_id'], ['cancers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cancers_anatomical_site'), 'cancers', ['anatomical_site'], unique=False)
    op.create_index(op.f('ix_cancers_canonical_name'), 'cancers', ['canonical_name'], unique=False)
    op.create_index(op.f('ix_cancers_slug'), 'cancers', ['slug'], unique=True)
    op.create_table('sources',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('organization_name', sa.String(length=255), nullable=False),
    sa.Column('source_name', sa.String(length=255), nullable=False),
    sa.Column('base_url', sa.String(length=512), nullable=False),
    sa.Column('country_code', sa.String(length=10), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('source_type', sa.String(length=100), nullable=False),
    sa.Column('trust_tier', sa.String(length=100), nullable=False),
    sa.Column('authority_type', sa.String(length=100), nullable=False),
    sa.Column('default_language', sa.String(length=10), nullable=True),
    sa.Column('supported_languages', sa.JSON(), nullable=True),
    sa.Column('license_type', sa.String(length=255), nullable=False),
    sa.Column('license_status', sa.String(length=50), nullable=False),
    sa.Column('reuse_allowed', sa.Boolean(), nullable=True),
    sa.Column('full_text_storage_allowed', sa.Boolean(), nullable=True),
    sa.Column('derived_summary_allowed', sa.Boolean(), nullable=True),
    sa.Column('attribution_required', sa.Boolean(), nullable=True),
    sa.Column('attribution_text', sa.String(length=512), nullable=True),
    sa.Column('reuse_policy_url', sa.String(length=512), nullable=True),
    sa.Column('terms_url', sa.String(length=512), nullable=True),
    sa.Column('robots_url', sa.String(length=512), nullable=True),
    sa.Column('ingestion_method', sa.String(length=50), nullable=True),
    sa.Column('crawl_frequency', sa.String(length=50), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.Column('last_reviewed', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sources_active'), 'sources', ['active'], unique=False)
    op.create_index(op.f('ix_sources_country_code'), 'sources', ['country_code'], unique=False)
    op.create_index(op.f('ix_sources_id'), 'sources', ['id'], unique=False)
    op.create_index(op.f('ix_sources_license_status'), 'sources', ['license_status'], unique=False)
    op.create_index(op.f('ix_sources_trust_tier'), 'sources', ['trust_tier'], unique=False)
    op.create_table('cancer_aliases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('cancer_id', sa.String(length=36), nullable=False),
    sa.Column('alias', sa.String(length=255), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('alias_type', sa.String(length=64), nullable=True),
    sa.Column('country_code', sa.String(length=10), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('review_status', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['cancer_id'], ['cancers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_alias_lookup', 'cancer_aliases', ['alias', 'language'], unique=False)
    op.create_index(op.f('ix_cancer_aliases_alias'), 'cancer_aliases', ['alias'], unique=False)
    op.create_index(op.f('ix_cancer_aliases_cancer_id'), 'cancer_aliases', ['cancer_id'], unique=False)
    op.create_index(op.f('ix_cancer_aliases_language'), 'cancer_aliases', ['language'], unique=False)
    op.create_table('consensus_facts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('cancer_id', sa.String(length=36), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('fact_key', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('clinical_detail', sa.Text(), nullable=True),
    sa.Column('corroboration_count', sa.Integer(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cancer_id'], ['cancers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_consensus_cancer_category', 'consensus_facts', ['cancer_id', 'category'], unique=False)
    op.create_index(op.f('ix_consensus_facts_active'), 'consensus_facts', ['active'], unique=False)
    op.create_index(op.f('ix_consensus_facts_cancer_id'), 'consensus_facts', ['cancer_id'], unique=False)
    op.create_index(op.f('ix_consensus_facts_category'), 'consensus_facts', ['category'], unique=False)
    op.create_index(op.f('ix_consensus_facts_fact_key'), 'consensus_facts', ['fact_key'], unique=False)
    op.create_table('content_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('canonical_cancer_id', sa.String(length=36), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('subcategory', sa.String(length=64), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_type', sa.String(length=64), nullable=True),
    sa.Column('country_code', sa.String(length=10), nullable=True),
    sa.Column('region_code', sa.String(length=32), nullable=True),
    sa.Column('jurisdiction_scope', sa.String(length=32), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('audience', sa.String(length=32), nullable=True),
    sa.Column('disagreement_status', sa.String(length=32), nullable=True),
    sa.Column('disagreement_notes', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['canonical_cancer_id'], ['cancers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_content_cancer_category', 'content_records', ['canonical_cancer_id', 'category'], unique=False)
    op.create_index('ix_content_filter', 'content_records', ['canonical_cancer_id', 'category', 'country_code', 'audience'], unique=False)
    op.create_index(op.f('ix_content_records_active'), 'content_records', ['active'], unique=False)
    op.create_index(op.f('ix_content_records_audience'), 'content_records', ['audience'], unique=False)
    op.create_index(op.f('ix_content_records_canonical_cancer_id'), 'content_records', ['canonical_cancer_id'], unique=False)
    op.create_index(op.f('ix_content_records_category'), 'content_records', ['category'], unique=False)
    op.create_index(op.f('ix_content_records_country_code'), 'content_records', ['country_code'], unique=False)
    op.create_index(op.f('ix_content_records_jurisdiction_scope'), 'content_records', ['jurisdiction_scope'], unique=False)
    op.create_index(op.f('ix_content_records_language'), 'content_records', ['language'], unique=False)
    op.create_index(op.f('ix_content_records_subcategory'), 'content_records', ['subcategory'], unique=False)
    op.create_table('ingestion_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('pages_discovered', sa.Integer(), nullable=True),
    sa.Column('pages_retrieved', sa.Integer(), nullable=True),
    sa.Column('pages_changed', sa.Integer(), nullable=True),
    sa.Column('records_created', sa.Integer(), nullable=True),
    sa.Column('records_updated', sa.Integer(), nullable=True),
    sa.Column('records_rejected', sa.Integer(), nullable=True),
    sa.Column('parser_failures', sa.Integer(), nullable=True),
    sa.Column('error_details', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingestion_jobs_source_id'), 'ingestion_jobs', ['source_id'], unique=False)
    op.create_table('source_documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('original_url', sa.String(length=1024), nullable=False),
    sa.Column('canonical_url', sa.String(length=1024), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('source_document_type', sa.String(length=64), nullable=True),
    sa.Column('source_cancer_name', sa.String(length=255), nullable=True),
    sa.Column('canonical_cancer_id', sa.String(length=36), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('country_code', sa.String(length=10), nullable=False),
    sa.Column('jurisdiction_scope', sa.String(length=32), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('source_updated_at', sa.DateTime(), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('http_etag', sa.String(length=128), nullable=True),
    sa.Column('http_last_modified', sa.String(length=128), nullable=True),
    sa.Column('parser_version', sa.String(length=32), nullable=True),
    sa.Column('processing_status', sa.String(length=32), nullable=True),
    sa.Column('license_status', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['canonical_cancer_id'], ['cancers.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_documents_canonical_cancer_id'), 'source_documents', ['canonical_cancer_id'], unique=False)
    op.create_index(op.f('ix_source_documents_content_hash'), 'source_documents', ['content_hash'], unique=False)
    op.create_index(op.f('ix_source_documents_original_url'), 'source_documents', ['original_url'], unique=False)
    op.create_index(op.f('ix_source_documents_source_id'), 'source_documents', ['source_id'], unique=False)
    op.create_table('source_health',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('last_check', sa.DateTime(), nullable=True),
    sa.Column('is_reachable', sa.Boolean(), nullable=True),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=True),
    sa.Column('last_successful_crawl', sa.DateTime(), nullable=True),
    sa.Column('alert_status', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_health_source_id'), 'source_health', ['source_id'], unique=False)
    op.create_table('consensus_fact_sources',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('consensus_fact_id', sa.String(length=36), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('source_url', sa.String(length=1024), nullable=False),
    sa.Column('quote_snippet', sa.Text(), nullable=True),
    sa.Column('attribution_text', sa.String(length=512), nullable=True),
    sa.Column('country_code', sa.String(length=10), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['consensus_fact_id'], ['consensus_facts.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consensus_fact_sources_consensus_fact_id'), 'consensus_fact_sources', ['consensus_fact_id'], unique=False)
    op.create_index(op.f('ix_consensus_fact_sources_country_code'), 'consensus_fact_sources', ['country_code'], unique=False)
    op.create_index(op.f('ix_consensus_fact_sources_source_id'), 'consensus_fact_sources', ['source_id'], unique=False)
    op.create_table('content_sources',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('content_record_id', sa.String(length=36), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('source_document_id', sa.String(length=36), nullable=True),
    sa.Column('source_url', sa.String(length=1024), nullable=False),
    sa.Column('source_updated_at', sa.DateTime(), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(), nullable=True),
    sa.Column('quote_snippet', sa.Text(), nullable=True),
    sa.Column('attribution_text', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['content_record_id'], ['content_records.id'], ),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_documents.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_sources_content_record_id'), 'content_sources', ['content_record_id'], unique=False)
    op.create_index(op.f('ix_content_sources_source_document_id'), 'content_sources', ['source_document_id'], unique=False)
    op.create_index(op.f('ix_content_sources_source_id'), 'content_sources', ['source_id'], unique=False)
    op.create_table('content_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('content_record_id', sa.String(length=36), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('change_type', sa.String(length=32), nullable=True),
    sa.Column('change_reason', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['content_record_id'], ['content_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_versions_content_record_id'), 'content_versions', ['content_record_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_content_versions_content_record_id'), table_name='content_versions')
    op.drop_table('content_versions')
    op.drop_index(op.f('ix_content_sources_source_id'), table_name='content_sources')
    op.drop_index(op.f('ix_content_sources_source_document_id'), table_name='content_sources')
    op.drop_index(op.f('ix_content_sources_content_record_id'), table_name='content_sources')
    op.drop_table('content_sources')
    op.drop_index(op.f('ix_consensus_fact_sources_source_id'), table_name='consensus_fact_sources')
    op.drop_index(op.f('ix_consensus_fact_sources_country_code'), table_name='consensus_fact_sources')
    op.drop_index(op.f('ix_consensus_fact_sources_consensus_fact_id'), table_name='consensus_fact_sources')
    op.drop_table('consensus_fact_sources')
    op.drop_index(op.f('ix_source_health_source_id'), table_name='source_health')
    op.drop_table('source_health')
    op.drop_index(op.f('ix_source_documents_source_id'), table_name='source_documents')
    op.drop_index(op.f('ix_source_documents_original_url'), table_name='source_documents')
    op.drop_index(op.f('ix_source_documents_content_hash'), table_name='source_documents')
    op.drop_index(op.f('ix_source_documents_canonical_cancer_id'), table_name='source_documents')
    op.drop_table('source_documents')
    op.drop_index(op.f('ix_ingestion_jobs_source_id'), table_name='ingestion_jobs')
    op.drop_table('ingestion_jobs')
    op.drop_index(op.f('ix_content_records_subcategory'), table_name='content_records')
    op.drop_index(op.f('ix_content_records_language'), table_name='content_records')
    op.drop_index(op.f('ix_content_records_jurisdiction_scope'), table_name='content_records')
    op.drop_index(op.f('ix_content_records_country_code'), table_name='content_records')
    op.drop_index(op.f('ix_content_records_category'), table_name='content_records')
    op.drop_index(op.f('ix_content_records_canonical_cancer_id'), table_name='content_records')
    op.drop_index(op.f('ix_content_records_audience'), table_name='content_records')
    op.drop_index(op.f('ix_content_records_active'), table_name='content_records')
    op.drop_index('ix_content_filter', table_name='content_records')
    op.drop_index('ix_content_cancer_category', table_name='content_records')
    op.drop_table('content_records')
    op.drop_index(op.f('ix_consensus_facts_fact_key'), table_name='consensus_facts')
    op.drop_index(op.f('ix_consensus_facts_category'), table_name='consensus_facts')
    op.drop_index(op.f('ix_consensus_facts_cancer_id'), table_name='consensus_facts')
    op.drop_index(op.f('ix_consensus_facts_active'), table_name='consensus_facts')
    op.drop_index('ix_consensus_cancer_category', table_name='consensus_facts')
    op.drop_table('consensus_facts')
    op.drop_index(op.f('ix_cancer_aliases_language'), table_name='cancer_aliases')
    op.drop_index(op.f('ix_cancer_aliases_cancer_id'), table_name='cancer_aliases')
    op.drop_index(op.f('ix_cancer_aliases_alias'), table_name='cancer_aliases')
    op.drop_index('ix_alias_lookup', table_name='cancer_aliases')
    op.drop_table('cancer_aliases')
    op.drop_index(op.f('ix_sources_trust_tier'), table_name='sources')
    op.drop_index(op.f('ix_sources_license_status'), table_name='sources')
    op.drop_index(op.f('ix_sources_id'), table_name='sources')
    op.drop_index(op.f('ix_sources_country_code'), table_name='sources')
    op.drop_index(op.f('ix_sources_active'), table_name='sources')
    op.drop_table('sources')
    op.drop_index(op.f('ix_cancers_slug'), table_name='cancers')
    op.drop_index(op.f('ix_cancers_canonical_name'), table_name='cancers')
    op.drop_index(op.f('ix_cancers_anatomical_site'), table_name='cancers')
    op.drop_table('cancers')
    # ### end Alembic commands ###
