"""
Document-Level Rights and Publication Decision Inventory (CIAPI-L004)

This module provides the authoritative, machine-readable inventory of document-level
rights decisions for candidate source documents in the CancerInfo API.

Guiding Principles:
1. Source-level metadata or licenses NEVER automatically clear individual documents.
2. Every exact canonical URL must have an explicit, auditable publication decision.
3. Fail-closed: documents lacking exact-url review evidence remain non-publication-eligible.
4. No external rights fabrication: do not assume clearance without explicit evidence.
"""
from dataclasses import asdict, dataclass
from datetime import datetime
from typing import Any, Dict, List, Optional
from sqlalchemy.orm import Session

from app.core.constants import PublicationStatus


@dataclass(frozen=True)
class DocumentRightsDecision:
    url: str
    source_id: str
    source_organization: str
    title: str
    canonical_cancer_slug: str
    country_code: str
    jurisdiction_scope: str
    publication_status: PublicationStatus
    rights_evidence_url: Optional[str]
    rights_reviewed_at: Optional[datetime]
    rights_reviewer: Optional[str]
    permissible_use: Optional[str]
    redistribution_allowed: bool
    commercial_redistribution_allowed: bool
    full_text_storage_allowed: bool
    derived_summary_allowed: bool
    attribution_required: bool
    attribution_text: Optional[str]
    reuse_restrictions: Optional[str]
    quarantine_reason: Optional[str]
    third_party_permission_status: Optional[str]
    third_party_permission_notes: Optional[str] = None

    def to_dict(self) -> Dict[str, Any]:
        data = asdict(self)
        data["publication_status"] = self.publication_status.value
        if self.rights_reviewed_at:
            data["rights_reviewed_at"] = self.rights_reviewed_at.isoformat()
        return data


# Authoritative Document-Level Rights Decisions for All 32 Launch Candidate Documents
RIGHTS_INVENTORY: Dict[str, DocumentRightsDecision] = {
    # --------------------------------------------------------------------------
    # National Cancer Institute (NCI) - 14 candidate URLs
    # Policy: Presumptive U.S. Federal Government work (17 U.S.C. § 105).
    # Decision: REVIEW_REQUIRED fail-closed awaiting exact-page third-party audit.
    # --------------------------------------------------------------------------
    "https://www.cancer.gov/types/breast": DocumentRightsDecision(
        url="https://www.cancer.gov/types/breast",
        source_id="nci-us",
        source_organization="National Cancer Institute",
        title="Breast Cancer Overview - National Cancer Institute",
        canonical_cancer_slug="breast-cancer",
        country_code="US",
        jurisdiction_scope="COUNTRY",
        publication_status=PublicationStatus.REVIEW_REQUIRED,
        rights_evidence_url="https://www.cancer.gov/policies/copyright-reuse",
        rights_reviewed_at=None,
        rights_reviewer=None,
        permissible_use="Presumptive U.S. Government work subject to item-level third-party audit",
        redistribution_allowed=False,
        commercial_redistribution_allowed=False,
        full_text_storage_allowed=True,
        derived_summary_allowed=True,
        attribution_required=True,
        attribution_text="Source: National Cancer Institute (NCI), U.S. National Institutes of Health.",
        reuse_restrictions="Text created by NCI is in public domain, but exact page review is required to verify absence of proprietary clinical diagrams or external guideline excerpts.",
        quarantine_reason="Awaiting exact-document audit for third-party medical illustrations, copyrighted summaries, or external guideline inclusions. Source-level public domain status does not confer automatic per-document clearance.",
        third_party_permission_status="UNREVIEWED",
    ),
    "https://www.cancer.gov/types/breast/screening": DocumentRightsDecision(
        url="https://www.cancer.gov/types/breast/screening",
        source_id="nci-us",
        source_organization="National Cancer Institute",
        title="Breast Cancer Screening Guidelines - NCI",
        canonical_cancer_slug="breast-cancer",
        country_code="US",
        jurisdiction_scope="COUNTRY",
        publication_status=PublicationStatus.REVIEW_REQUIRED,
        rights_evidence_url="https://www.cancer.gov/policies/copyright-reuse",
        rights_reviewed_at=None,
        rights_reviewer=None,
        permissible_use="Presumptive U.S. Government work subject to item-level third-party audit",
        redistribution_allowed=False,
        commercial_redistribution_allowed=False,
        full_text_storage_allowed=True,
        derived_summary_allowed=True,
        attribution_required=True,
        attribution_text="Source: National Cancer Institute (NCI), U.S. National Institutes of Health.",
        reuse_restrictions="Guidelines may quote USPSTF or third-party professional society recommendations that carry separate copyright protections.",
        quarantine_reason="Awaiting item-level verification of external guideline text and third-party recommendations.",
        third_party_permission_status="UNREVIEWED",
    ),
    "https://www.cancer.gov/types/breast/symptoms": DocumentRightsDecision(
        url="https://www.cancer.gov/types/breast/symptoms",
        source_id="nci-us",
        source_organization="National Cancer Institute",
        title="Breast Cancer Symptoms - NCI",
        canonical_cancer_slug="breast-cancer",
        country_code="US",
        jurisdiction_scope="COUNTRY",
        publication_status=PublicationStatus.REVIEW_REQUIRED,
        rights_evidence_url="https://www.cancer.gov/policies/copyright-reuse",
        rights_reviewed_at=None,
        rights_reviewer=None,
        permissible_use="Presumptive U.S. Government work subject to item-level third-party audit",
        redistribution_allowed=False,
        commercial_redistribution_allowed=False,
        full_text_storage_allowed=True,
        derived_summary_allowed=True,
        attribution_required=True,
        attribution_text="Source: National Cancer Institute (NCI), U.S. National Institutes of Health.",
        reuse_restrictions="May contain medical illustration diagrams subject to third-party medical animator licensing.",
        quarantine_reason="Awaiting exact-document audit for embedded illustrations and third-party clinical media.",
        third_party_permission_status="UNREVIEWED",
    ),
    "https://www.cancer.gov/types/breast/treatment": DocumentRightsDecision(
        url="https://www.cancer.gov/types/breast/treatment",
        source_id="nci-us",
        source_organization="National Cancer Institute",
        title="Breast Cancer Treatment Options - NCI",
        canonical_cancer_slug="breast-cancer",
        country_code="US",
        jurisdiction_scope="COUNTRY",
        publication_status=PublicationStatus.REVIEW_REQUIRED,
        rights_evidence_url="https://www.cancer.gov/policies/copyright-reuse",
        rights_reviewed_at=None,
        rights_reviewer=None,
        permissible_use="Presumptive U.S. Government work subject to item-level third-party audit",
        redistribution_allowed=False,
        commercial_redistribution_allowed=False,
        full_text_storage_allowed=True,
        derived_summary_allowed=True,
        attribution_required=True,
        attribution_text="Source: National Cancer Institute (NCI), U.S. National Institutes of Health.",
        reuse_restrictions="PDQ treatment summaries are written by editorial boards; certain tables and drug descriptions may reference proprietary clinical studies.",
        quarantine_reason="Awaiting exact-document verification of clinical study tables and proprietary drug references.",
        third_party_permission_status="UNREVIEWED",
    ),
    "https://www.cancer.gov/types/cervical/symptoms": DocumentRightsDecision(
        url="https://www.cancer.gov/types/cervical/symptoms",
        source_id="nci-us",
        source_organization="National Cancer Institute",
        title="Cervical Cancer Symptoms - NCI",
        canonical_cancer_slug="cervical-cancer",
        country_code="US",
        jurisdiction_scope="COUNTRY",
        publication_status=PublicationStatus.REVIEW_REQUIRED,
        rights_evidence_url="https://www.cancer.gov/policies/copyright-reuse",
        rights_reviewed_at=None,
        rights_reviewer=None,
        permissible_use="Presumptive U.S. Government work subject to item-level third-party audit",
        redistribution_allowed=False,
        commercial_redistribution_allowed=False,
        full_text_storage_allowed=True,
        derived_summary_allowed=True,
        attribution_required=True,
        attribution_text="Source: National Cancer Institute (NCI), U.S. National Institutes of Health.",
        reuse_restrictions="Subject to verification of clinical infographics and third-party media.",
        quarantine_reason="Consensus-only citation awaiting exact-page review for third-party media and external citations.",
        third_party_permission_status="UNREVIEWED",
    ),
    "https://www.cancer.gov/types/colorectal": DocumentRightsDecision(
        url="https://www.cancer.gov/types/colorectal",
        source_id="nci-us",
        source_organization="National Cancer Institute",
        title="Colorectal Cancer Overview - NCI",
        canonical_cancer_slug="colorectal-cancer",
        country_code="US",
        jurisdiction_scope="COUNTRY",
        publication_status=PublicationStatus.REVIEW_REQUIRED,
        rights_evidence_url="https://www.cancer.gov/policies/copyright-reuse",
        rights_reviewed_at=None,
        rights_reviewer=None,
        permissible_use="Presumptive U.S. Government work subject to item-level third-party audit",
        redistribution_allowed=False,
        commercial_redistribution_allowed=False,
        full_text_storage_allowed=True,
        derived_summary_allowed=True,
        attribution_required=True,
        attribution_text="Source: National Cancer Institute (NCI), U.S. National Institutes of Health.",
        reuse_restrictions="Subject to verification of anatomical diagrams and SEER statistical summaries.",
        quarantine_reason="Awaiting exact-document audit for anatomical graphics and proprietary statistics.",
        third_party_permission_status="UNREVIEWED",
    ),
    "https://www.cancer.gov/types/colorectal/symptoms": DocumentRightsDecision(
        url="https://www.cancer.gov/types/colorectal/symptoms",
        source_id="nci-us",
        source_organization="National Cancer Institute",
        title="Colorectal Cancer Symptoms - NCI",
        canonical_cancer_slug="colorectal-cancer",
        country_code="US",
        jurisdiction_scope="COUNTRY",
        publication_status=PublicationStatus.REVIEW_REQUIRED,
        rights_evidence_url="https://www.cancer.gov/policies/copyright-reuse",
        rights_reviewed_at=None,
        rights_reviewer=None,
        permissible_use="Presumptive U.S. Government work subject to item-level third-party audit",
        redistribution_allowed=False,
        commercial_redistribution_allowed=False,
        full_text_storage_allowed=True,
        derived_summary_allowed=True,
        attribution_required=True,
        attribution_text="Source: National Cancer Institute (NCI), U.S. National Institutes of Health.",
        reuse_restrictions="Subject to verification of clinical symptom lists and patient education media.",
        quarantine_reason="Awaiting exact-document audit for embedded illustrations and third-party media.",
        third_party_permission_status="UNREVIEWED",
    ),
    "https://www.cancer.gov/types/lung": DocumentRightsDecision(
        url="https://www.cancer.gov/types/lung",
        source_id="nci-us",
        source_organization="National Cancer Institute",
        title="Lung Cancer Overview - NCI",
        canonical_cancer_slug="lung-cancer",
        country_code="US",
        jurisdiction_scope="COUNTRY",
        publication_status=PublicationStatus.REVIEW_REQUIRED,
        rights_evidence_url="https://www.cancer.gov/policies/copyright-reuse",
        rights_reviewed_at=None,
        rights_reviewer=None,
        permissible_use="Presumptive U.S. Government work subject to item-level third-party audit",
        redistribution_allowed=False,
        commercial_redistribution_allowed=False,
        full_text_storage_allowed=True,
        derived_summary_allowed=True,
        attribution_required=True,
        attribution_text="Source: National Cancer Institute (NCI), U.S. National Institutes of Health.",
        reuse_restrictions="Subject to verification of thoracic anatomy illustrations and histological subtype classifications.",
        quarantine_reason="Awaiting exact-document audit for histological images and medical media.",
        third_party_permission_status="UNREVIEWED",
    ),
    "https://www.cancer.gov/types/lung/symptoms": DocumentRightsDecision(
        url="https://www.cancer.gov/types/lung/symptoms",
        source_id="nci-us",
        source_organization="National Cancer Institute",
        title="Lung Cancer Symptoms - NCI",
        canonical_cancer_slug="lung-cancer",
        country_code="US",
        jurisdiction_scope="COUNTRY",
        publication_status=PublicationStatus.REVIEW_REQUIRED,
        rights_evidence_url="https://www.cancer.gov/policies/copyright-reuse",
        rights_reviewed_at=None,
        rights_reviewer=None,
        permissible_use="Presumptive U.S. Government work subject to item-level third-party audit",
        redistribution_allowed=False,
        commercial_redistribution_allowed=False,
        full_text_storage_allowed=True,
        derived_summary_allowed=True,
        attribution_required=True,
        attribution_text="Source: National Cancer Institute (NCI), U.S. National Institutes of Health.",
        reuse_restrictions="Subject to verification of symptom guides and clinical flowcharts.",
        quarantine_reason="Awaiting exact-document audit for diagnostic flowchart diagrams and external citations.",
        third_party_permission_status="UNREVIEWED",
    ),
    "https://www.cancer.gov/types/pancreatic": DocumentRightsDecision(
        url="https://www.cancer.gov/types/pancreatic",
        source_id="nci-us",
        source_organization="National Cancer Institute",
        title="Pancreatic Cancer Overview - NCI",
        canonical_cancer_slug="pancreatic-cancer",
        country_code="US",
        jurisdiction_scope="COUNTRY",
        publication_status=PublicationStatus.REVIEW_REQUIRED,
        rights_evidence_url="https://www.cancer.gov/policies/copyright-reuse",
        rights_reviewed_at=None,
        rights_reviewer=None,
        permissible_use="Presumptive U.S. Government work subject to item-level third-party audit",
        redistribution_allowed=False,
        commercial_redistribution_allowed=False,
        full_text_storage_allowed=True,
        derived_summary_allowed=True,
        attribution_required=True,
        attribution_text="Source: National Cancer Institute (NCI), U.S. National Institutes of Health.",
        reuse_restrictions="Subject to verification of endocrine/exocrine medical illustrations.",
        quarantine_reason="Awaiting exact-document audit for medical diagrams and clinical text provenance.",
        third_party_permission_status="UNREVIEWED",
    ),
    "https://www.cancer.gov/types/pancreatic/symptoms": DocumentRightsDecision(
        url="https://www.cancer.gov/types/pancreatic/symptoms",
        source_id="nci-us",
        source_organization="National Cancer Institute",
        title="Pancreatic Cancer Symptoms - NCI",
        canonical_cancer_slug="pancreatic-cancer",
        country_code="US",
        jurisdiction_scope="COUNTRY",
        publication_status=PublicationStatus.REVIEW_REQUIRED,
        rights_evidence_url="https://www.cancer.gov/policies/copyright-reuse",
        rights_reviewed_at=None,
        rights_reviewer=None,
        permissible_use="Presumptive U.S. Government work subject to item-level third-party audit",
        redistribution_allowed=False,
        commercial_redistribution_allowed=False,
        full_text_storage_allowed=True,
        derived_summary_allowed=True,
        attribution_required=True,
        attribution_text="Source: National Cancer Institute (NCI), U.S. National Institutes of Health.",
        reuse_restrictions="Subject to verification of clinical symptom presentation descriptions.",
        quarantine_reason="Awaiting exact-document audit for third-party clinical contributions.",
        third_party_permission_status="UNREVIEWED",
    ),
    "https://www.cancer.gov/types/prostate": DocumentRightsDecision(
        url="https://www.cancer.gov/types/prostate",
        source_id="nci-us",
        source_organization="National Cancer Institute",
        title="Prostate Cancer Overview - NCI",
        canonical_cancer_slug="prostate-cancer",
        country_code="US",
        jurisdiction_scope="COUNTRY",
        publication_status=PublicationStatus.REVIEW_REQUIRED,
        rights_evidence_url="https://www.cancer.gov/policies/copyright-reuse",
        rights_reviewed_at=None,
        rights_reviewer=None,
        permissible_use="Presumptive U.S. Government work subject to item-level third-party audit",
        redistribution_allowed=False,
        commercial_redistribution_allowed=False,
        full_text_storage_allowed=True,
        derived_summary_allowed=True,
        attribution_required=True,
        attribution_text="Source: National Cancer Institute (NCI), U.S. National Institutes of Health.",
        reuse_restrictions="Subject to verification of male pelvic anatomy illustrations and grading scale references (Gleason/Grade Groups).",
        quarantine_reason="Awaiting exact-document audit for anatomical illustrations and grading diagrams.",
        third_party_permission_status="UNREVIEWED",
    ),
    "https://www.cancer.gov/types/prostate/symptoms": DocumentRightsDecision(
        url="https://www.cancer.gov/types/prostate/symptoms",
        source_id="nci-us",
        source_organization="National Cancer Institute",
        title="Prostate Cancer Symptoms - NCI",
        canonical_cancer_slug="prostate-cancer",
        country_code="US",
        jurisdiction_scope="COUNTRY",
        publication_status=PublicationStatus.REVIEW_REQUIRED,
        rights_evidence_url="https://www.cancer.gov/policies/copyright-reuse",
        rights_reviewed_at=None,
        rights_reviewer=None,
        permissible_use="Presumptive U.S. Government work subject to item-level third-party audit",
        redistribution_allowed=False,
        commercial_redistribution_allowed=False,
        full_text_storage_allowed=True,
        derived_summary_allowed=True,
        attribution_required=True,
        attribution_text="Source: National Cancer Institute (NCI), U.S. National Institutes of Health.",
        reuse_restrictions="Subject to verification of patient education presentation descriptions.",
        quarantine_reason="Awaiting exact-document audit for clinical symptom text and media.",
        third_party_permission_status="UNREVIEWED",
    ),
    "https://www.cancer.gov/types/skin/symptoms": DocumentRightsDecision(
        url="https://www.cancer.gov/types/skin/symptoms",
        source_id="nci-us",
        source_organization="National Cancer Institute",
        title="Skin Cancer and Melanoma Symptoms - NCI",
        canonical_cancer_slug="melanoma",
        country_code="US",
        jurisdiction_scope="COUNTRY",
        publication_status=PublicationStatus.REVIEW_REQUIRED,
        rights_evidence_url="https://www.cancer.gov/policies/copyright-reuse",
        rights_reviewed_at=None,
        rights_reviewer=None,
        permissible_use="Presumptive U.S. Government work subject to item-level third-party audit",
        redistribution_allowed=False,
        commercial_redistribution_allowed=False,
        full_text_storage_allowed=True,
        derived_summary_allowed=True,
        attribution_required=True,
        attribution_text="Source: National Cancer Institute (NCI), U.S. National Institutes of Health.",
        reuse_restrictions="ABCDE photographic melanoma guides frequently license clinical photographs from dermatological societies.",
        quarantine_reason="Consensus citation; high risk of third-party clinical photograph copyright in dermatological ABCDE guides.",
        third_party_permission_status="UNREVIEWED",
    ),

    # --------------------------------------------------------------------------
    # National Health Service (NHS UK) - 9 candidate URLs
    # Policy: Open Government Licence v3.0 (OGL v3.0).
    # Decision: REVIEW_REQUIRED fail-closed awaiting exact-page third-party audit.
    # --------------------------------------------------------------------------
    "https://www.nhs.uk/conditions/bowel-cancer-screening/": DocumentRightsDecision(
        url="https://www.nhs.uk/conditions/bowel-cancer-screening/",
        source_id="nhs-uk",
        source_organization="National Health Service",
        title="NHS Bowel Cancer Screening Programme",
        canonical_cancer_slug="colorectal-cancer",
        country_code="GB",
        jurisdiction_scope="COUNTRY",
        publication_status=PublicationStatus.REVIEW_REQUIRED,
        rights_evidence_url="https://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/",
        rights_reviewed_at=None,
        rights_reviewer=None,
        permissible_use="Presumptive Open Government Licence v3.0 subject to exact-document verification",
        redistribution_allowed=False,
        commercial_redistribution_allowed=False,
        full_text_storage_allowed=True,
        derived_summary_allowed=True,
        attribution_required=True,
        attribution_text="Source: NHS (National Health Service, United Kingdom). Contains public sector information licensed under the Open Government Licence v3.0.",
        reuse_restrictions="OGL v3.0 excludes third-party materials, departmental logos, and proprietary screening kit instructions.",
        quarantine_reason="Awaiting exact-document verification under OGL v3.0 to confirm absence of proprietary screening kit imagery or third-party guidelines.",
        third_party_permission_status="UNREVIEWED",
    ),
    "https://www.nhs.uk/conditions/bowel-cancer/symptoms/": DocumentRightsDecision(
        url="https://www.nhs.uk/conditions/bowel-cancer/symptoms/",
        source_id="nhs-uk",
        source_organization="National Health Service",
        title="Bowel Cancer Symptoms - NHS",
        canonical_cancer_slug="colorectal-cancer",
        country_code="GB",
        jurisdiction_scope="COUNTRY",
        publication_status=PublicationStatus.REVIEW_REQUIRED,
        rights_evidence_url="https://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/",
        rights_reviewed_at=None,
        rights_reviewer=None,
        permissible_use="Presumptive Open Government Licence v3.0 subject to exact-document verification",
        redistribution_allowed=False,
        commercial_redistribution_allowed=False,
        full_text_storage_allowed=True,
        derived_summary_allowed=True,
        attribution_required=True,
        attribution_text="Source: NHS (National Health Service, United Kingdom). Contains public sector information licensed under the Open Government Licence v3.0.",
        reuse_restrictions="OGL v3.0 excludes third-party clinical imagery, case studies, and partner content.",
        quarantine_reason="Awaiting exact-document audit for third-party licensed patient photography and clinical graphics.",
        third_party_permission_status="UNREVIEWED",
    ),
    "https://www.nhs.uk/conditions/breast-cancer/symptoms/": DocumentRightsDecision(
        url="https://www.nhs.uk/conditions/breast-cancer/symptoms/",
        source_id="nhs-uk",
        source_organization="National Health Service",
        title="Breast Cancer Symptoms - NHS",
        canonical_cancer_slug="breast-cancer",
        country_code="GB",
        jurisdiction_scope="COUNTRY",
        publication_status=PublicationStatus.REVIEW_REQUIRED,
        rights_evidence_url="https://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/",
        rights_reviewed_at=None,
        rights_reviewer=None,
        permissible_use="Presumptive Open Government Licence v3.0 subject to exact-document verification",
        redistribution_allowed=False,
        commercial_redistribution_allowed=False,
        full_text_storage_allowed=True,
        derived_summary_allowed=True,
        attribution_required=True,
        attribution_text="Source: NHS (National Health Service, United Kingdom). Contains public sector information licensed under the Open Government Licence v3.0.",
        reuse_restrictions="Subject to verification of clinical symptom presentation illustrations.",
        quarantine_reason="Awaiting exact-document audit for clinical symptom media and proprietary partner contributions.",
        third_party_permission_status="UNREVIEWED",
    ),
    "https://www.nhs.uk/conditions/breast-screening-mammogram/": DocumentRightsDecision(
        url="https://www.nhs.uk/conditions/breast-screening-mammogram/",
        source_id="nhs-uk",
        source_organization="National Health Service",
        title="NHS Breast Screening Programme",
        canonical_cancer_slug="breast-cancer",
        country_code="GB",
        jurisdiction_scope="COUNTRY",
        publication_status=PublicationStatus.REVIEW_REQUIRED,
        rights_evidence_url="https://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/",
        rights_reviewed_at=None,
        rights_reviewer=None,
        permissible_use="Presumptive Open Government Licence v3.0 subject to exact-document verification",
        redistribution_allowed=False,
        commercial_redistribution_allowed=False,
        full_text_storage_allowed=True,
        derived_summary_allowed=True,
        attribution_required=True,
        attribution_text="Source: NHS (National Health Service, United Kingdom). Contains public sector information licensed under the Open Government Licence v3.0.",
        reuse_restrictions="Subject to verification of screening clinic equipment images and NHS visual identity.",
        quarantine_reason="Awaiting exact-document verification of clinical equipment photos and guideline references.",
        third_party_permission_status="UNREVIEWED",
    ),
    "https://www.nhs.uk/conditions/cervical-cancer/symptoms/": DocumentRightsDecision(
        url="https://www.nhs.uk/conditions/cervical-cancer/symptoms/",
        source_id="nhs-uk",
        source_organization="National Health Service",
        title="Cervical Cancer Symptoms - NHS",
        canonical_cancer_slug="cervical-cancer",
        country_code="GB",
        jurisdiction_scope="COUNTRY",
        publication_status=PublicationStatus.REVIEW_REQUIRED,
        rights_evidence_url="https://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/",
        rights_reviewed_at=None,
        rights_reviewer=None,
        permissible_use="Presumptive Open Government Licence v3.0 subject to exact-document verification",
        redistribution_allowed=False,
        commercial_redistribution_allowed=False,
        full_text_storage_allowed=True,
        derived_summary_allowed=True,
        attribution_required=True,
        attribution_text="Source: NHS (National Health Service, United Kingdom). Contains public sector information licensed under the Open Government Licence v3.0.",
        reuse_restrictions="Consensus citation; subject to verification of third-party clinical illustrations.",
        quarantine_reason="Consensus citation awaiting exact-page review for third-party media under OGL v3.0.",
        third_party_permission_status="UNREVIEWED",
    ),
    "https://www.nhs.uk/conditions/lung-cancer/symptoms/": DocumentRightsDecision(
        url="https://www.nhs.uk/conditions/lung-cancer/symptoms/",
        source_id="nhs-uk",
        source_organization="National Health Service",
        title="Lung Cancer Symptoms - NHS",
        canonical_cancer_slug="lung-cancer",
        country_code="GB",
        jurisdiction_scope="COUNTRY",
        publication_status=PublicationStatus.REVIEW_REQUIRED,
        rights_evidence_url="https://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/",
        rights_reviewed_at=None,
        rights_reviewer=None,
        permissible_use="Presumptive Open Government Licence v3.0 subject to exact-document verification",
        redistribution_allowed=False,
        commercial_redistribution_allowed=False,
        full_text_storage_allowed=True,
        derived_summary_allowed=True,
        attribution_required=True,
        attribution_text="Source: NHS (National Health Service, United Kingdom). Contains public sector information licensed under the Open Government Licence v3.0.",
        reuse_restrictions="Subject to verification of thoracic symptom graphics.",
        quarantine_reason="Consensus citation awaiting exact-page review for third-party imagery.",
        third_party_permission_status="UNREVIEWED",
    ),
    "https://www.nhs.uk/conditions/melanoma-skin-cancer/symptoms/": DocumentRightsDecision(
        url="https://www.nhs.uk/conditions/melanoma-skin-cancer/symptoms/",
        source_id="nhs-uk",
        source_organization="National Health Service",
        title="Melanoma Skin Cancer Symptoms - NHS",
        canonical_cancer_slug="melanoma",
        country_code="GB",
        jurisdiction_scope="COUNTRY",
        publication_status=PublicationStatus.REVIEW_REQUIRED,
        rights_evidence_url="https://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/",
        rights_reviewed_at=None,
        rights_reviewer=None,
        permissible_use="Presumptive Open Government Licence v3.0 subject to exact-document verification",
        redistribution_allowed=False,
        commercial_redistribution_allowed=False,
        full_text_storage_allowed=True,
        derived_summary_allowed=True,
        attribution_required=True,
        attribution_text="Source: NHS (National Health Service, United Kingdom). Contains public sector information licensed under the Open Government Licence v3.0.",
        reuse_restrictions="Melanoma ABCDE photographs on NHS pages are frequently credited to the British Association of Dermatologists (BAD) or clinical photography departments.",
        quarantine_reason="Consensus citation; high probability of third-party clinical dermatological copyright on ABCDE images.",
        third_party_permission_status="UNREVIEWED",
    ),
    "https://www.nhs.uk/conditions/pancreatic-cancer/symptoms/": DocumentRightsDecision(
        url="https://www.nhs.uk/conditions/pancreatic-cancer/symptoms/",
        source_id="nhs-uk",
        source_organization="National Health Service",
        title="Pancreatic Cancer Symptoms - NHS",
        canonical_cancer_slug="pancreatic-cancer",
        country_code="GB",
        jurisdiction_scope="COUNTRY",
        publication_status=PublicationStatus.REVIEW_REQUIRED,
        rights_evidence_url="https://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/",
        rights_reviewed_at=None,
        rights_reviewer=None,
        permissible_use="Presumptive Open Government Licence v3.0 subject to exact-document verification",
        redistribution_allowed=False,
        commercial_redistribution_allowed=False,
        full_text_storage_allowed=True,
        derived_summary_allowed=True,
        attribution_required=True,
        attribution_text="Source: NHS (National Health Service, United Kingdom). Contains public sector information licensed under the Open Government Licence v3.0.",
        reuse_restrictions="Subject to verification of clinical presentations.",
        quarantine_reason="Consensus citation awaiting exact-page review for third-party media under OGL v3.0.",
        third_party_permission_status="UNREVIEWED",
    ),
    "https://www.nhs.uk/conditions/prostate-cancer/symptoms/": DocumentRightsDecision(
        url="https://www.nhs.uk/conditions/prostate-cancer/symptoms/",
        source_id="nhs-uk",
        source_organization="National Health Service",
        title="Prostate Cancer Symptoms - NHS",
        canonical_cancer_slug="prostate-cancer",
        country_code="GB",
        jurisdiction_scope="COUNTRY",
        publication_status=PublicationStatus.REVIEW_REQUIRED,
        rights_evidence_url="https://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/",
        rights_reviewed_at=None,
        rights_reviewer=None,
        permissible_use="Presumptive Open Government Licence v3.0 subject to exact-document verification",
        redistribution_allowed=False,
        commercial_redistribution_allowed=False,
        full_text_storage_allowed=True,
        derived_summary_allowed=True,
        attribution_required=True,
        attribution_text="Source: NHS (National Health Service, United Kingdom). Contains public sector information licensed under the Open Government Licence v3.0.",
        reuse_restrictions="Subject to verification of clinical text and partner guidelines.",
        quarantine_reason="Consensus citation awaiting exact-page review for third-party media under OGL v3.0.",
        third_party_permission_status="UNREVIEWED",
    ),

    # --------------------------------------------------------------------------
    # World Health Organization (WHO) - 4 candidate URLs
    # Policy: CC BY-NC-SA 3.0 IGO (Non-Commercial, Share-Alike).
    # Decision: PERMISSION_PENDING / QUARANTINED due to commercial/API restriction.
    # --------------------------------------------------------------------------
    "https://www.who.int/news-room/fact-sheets/detail/breast-cancer": DocumentRightsDecision(
        url="https://www.who.int/news-room/fact-sheets/detail/breast-cancer",
        source_id="who-global",
        source_organization="World Health Organization",
        title="Breast Cancer Fact Sheet - WHO",
        canonical_cancer_slug="breast-cancer",
        country_code="GLOBAL",
        jurisdiction_scope="GLOBAL",
        publication_status=PublicationStatus.PERMISSION_PENDING,
        rights_evidence_url="https://www.who.int/about/policies/publishing/open-access",
        rights_reviewed_at=None,
        rights_reviewer=None,
        permissible_use="Non-commercial research/educational only under CC BY-NC-SA 3.0 IGO",
        redistribution_allowed=False,
        commercial_redistribution_allowed=False,
        full_text_storage_allowed=True,
        derived_summary_allowed=True,
        attribution_required=True,
        attribution_text="Source: World Health Organization (WHO). Licensed under CC BY-NC-SA 3.0 IGO.",
        reuse_restrictions="CC BY-NC-SA 3.0 IGO prohibits commercial use and requires share-alike adaptation licensing. Public/commercial API distribution is not permitted without explicit written agreement from WHO.",
        quarantine_reason="WHO CC BY-NC-SA 3.0 IGO non-commercial restriction and redistribution conditions are unresolved for public/commercial API consumption. A free API cannot be presumed non-commercial. Written permission or commercial waiver required.",
        third_party_permission_status="PENDING",
        third_party_permission_notes="Formal permission request for API distribution pending submission to WHO permissions team.",
    ),
    "https://www.who.int/news-room/fact-sheets/detail/cancer": DocumentRightsDecision(
        url="https://www.who.int/news-room/fact-sheets/detail/cancer",
        source_id="who-global",
        source_organization="World Health Organization",
        title="Cancer Fact Sheet - WHO",
        canonical_cancer_slug="lung-cancer",
        country_code="GLOBAL",
        jurisdiction_scope="GLOBAL",
        publication_status=PublicationStatus.PERMISSION_PENDING,
        rights_evidence_url="https://www.who.int/about/policies/publishing/open-access",
        rights_reviewed_at=None,
        rights_reviewer=None,
        permissible_use="Non-commercial research/educational only under CC BY-NC-SA 3.0 IGO",
        redistribution_allowed=False,
        commercial_redistribution_allowed=False,
        full_text_storage_allowed=True,
        derived_summary_allowed=True,
        attribution_required=True,
        attribution_text="Source: World Health Organization (WHO). Licensed under CC BY-NC-SA 3.0 IGO.",
        reuse_restrictions="Non-commercial restriction applies. Commercial/API distribution forbidden without explicit waiver.",
        quarantine_reason="Consensus citation; WHO CC BY-NC-SA 3.0 IGO non-commercial license restriction prevents public/commercial API redistribution without written permission.",
        third_party_permission_status="PENDING",
        third_party_permission_notes="Pending commercial waiver or formal permission from WHO.",
    ),
    "https://www.who.int/news-room/fact-sheets/detail/cervical-cancer": DocumentRightsDecision(
        url="https://www.who.int/news-room/fact-sheets/detail/cervical-cancer",
        source_id="who-global",
        source_organization="World Health Organization",
        title="Cervical Cancer Fact Sheet - WHO",
        canonical_cancer_slug="cervical-cancer",
        country_code="GLOBAL",
        jurisdiction_scope="GLOBAL",
        publication_status=PublicationStatus.PERMISSION_PENDING,
        rights_evidence_url="https://www.who.int/about/policies/publishing/open-access",
        rights_reviewed_at=None,
        rights_reviewer=None,
        permissible_use="Non-commercial research/educational only under CC BY-NC-SA 3.0 IGO",
        redistribution_allowed=False,
        commercial_redistribution_allowed=False,
        full_text_storage_allowed=True,
        derived_summary_allowed=True,
        attribution_required=True,
        attribution_text="Source: World Health Organization (WHO). Licensed under CC BY-NC-SA 3.0 IGO.",
        reuse_restrictions="Non-commercial restriction applies. Commercial/API distribution forbidden without explicit waiver.",
        quarantine_reason="Consensus citation; WHO CC BY-NC-SA 3.0 IGO non-commercial license restriction prevents public/commercial API redistribution without written permission.",
        third_party_permission_status="PENDING",
        third_party_permission_notes="Pending commercial waiver or formal permission from WHO.",
    ),
    "https://www.who.int/news-room/fact-sheets/detail/lung-cancer": DocumentRightsDecision(
        url="https://www.who.int/news-room/fact-sheets/detail/lung-cancer",
        source_id="who-global",
        source_organization="World Health Organization",
        title="Lung Cancer Risk Factors - WHO",
        canonical_cancer_slug="lung-cancer",
        country_code="GLOBAL",
        jurisdiction_scope="GLOBAL",
        publication_status=PublicationStatus.PERMISSION_PENDING,
        rights_evidence_url="https://www.who.int/about/policies/publishing/open-access",
        rights_reviewed_at=None,
        rights_reviewer=None,
        permissible_use="Non-commercial research/educational only under CC BY-NC-SA 3.0 IGO",
        redistribution_allowed=False,
        commercial_redistribution_allowed=False,
        full_text_storage_allowed=True,
        derived_summary_allowed=True,
        attribution_required=True,
        attribution_text="Source: World Health Organization (WHO). Licensed under CC BY-NC-SA 3.0 IGO.",
        reuse_restrictions="Non-commercial restriction applies. Commercial/API distribution forbidden without explicit waiver.",
        quarantine_reason="WHO CC BY-NC-SA 3.0 IGO non-commercial restriction prevents public/commercial API redistribution without written permission.",
        third_party_permission_status="PENDING",
        third_party_permission_notes="Pending commercial waiver or formal permission from WHO.",
    ),

    # --------------------------------------------------------------------------
    # Cancer Australia - 4 candidate URLs
    # Policy: CC BY 4.0 subject to Australian Crown copyright and third-party exceptions.
    # Decision: REVIEW_REQUIRED fail-closed; blanket label does not clear pages.
    # --------------------------------------------------------------------------
    "https://www.canceraustralia.gov.au/affected-cancer/cancer-types/bowel-cancer/symptoms": DocumentRightsDecision(
        url="https://www.canceraustralia.gov.au/affected-cancer/cancer-types/bowel-cancer/symptoms",
        source_id="cancer-australia",
        source_organization="Cancer Australia",
        title="Bowel Cancer Symptoms - Cancer Australia",
        canonical_cancer_slug="colorectal-cancer",
        country_code="AU",
        jurisdiction_scope="COUNTRY",
        publication_status=PublicationStatus.REVIEW_REQUIRED,
        rights_evidence_url="https://www.canceraustralia.gov.au/copyright",
        rights_reviewed_at=None,
        rights_reviewer=None,
        permissible_use="Pending item-level rights audit; subject to Commonwealth of Australia Crown copyright terms",
        redistribution_allowed=False,
        commercial_redistribution_allowed=False,
        full_text_storage_allowed=True,
        derived_summary_allowed=True,
        attribution_required=True,
        attribution_text="Source: Cancer Australia, Australian Government. Licensed under CC BY 4.0.",
        reuse_restrictions="Blanket CC BY 4.0 source statement excludes third-party material, agency branding, and materials subject to separate Crown copyright conditions.",
        quarantine_reason="Source-level CC BY 4.0 label cannot be used as automatic blanket clearance. Exact documents remain non-publication-eligible until individual page review verifies absence of third-party restrictions or Crown copyright carve-outs.",
        third_party_permission_status="REVIEW_REQUIRED",
    ),
    "https://www.canceraustralia.gov.au/affected-cancer/cancer-types/lung-cancer/symptoms": DocumentRightsDecision(
        url="https://www.canceraustralia.gov.au/affected-cancer/cancer-types/lung-cancer/symptoms",
        source_id="cancer-australia",
        source_organization="Cancer Australia",
        title="Lung Cancer Symptoms - Cancer Australia",
        canonical_cancer_slug="lung-cancer",
        country_code="AU",
        jurisdiction_scope="COUNTRY",
        publication_status=PublicationStatus.REVIEW_REQUIRED,
        rights_evidence_url="https://www.canceraustralia.gov.au/copyright",
        rights_reviewed_at=None,
        rights_reviewer=None,
        permissible_use="Pending item-level rights audit; subject to Commonwealth of Australia Crown copyright terms",
        redistribution_allowed=False,
        commercial_redistribution_allowed=False,
        full_text_storage_allowed=True,
        derived_summary_allowed=True,
        attribution_required=True,
        attribution_text="Source: Cancer Australia, Australian Government. Licensed under CC BY 4.0.",
        reuse_restrictions="Subject to third-party copyright exceptions and Australian Crown copyright conditions.",
        quarantine_reason="Consensus citation; source-level CC BY 4.0 is unverified for this exact document. Item-level audit required under Crown copyright.",
        third_party_permission_status="REVIEW_REQUIRED",
    ),
    "https://www.canceraustralia.gov.au/affected-cancer/cancer-types/melanoma/symptoms": DocumentRightsDecision(
        url="https://www.canceraustralia.gov.au/affected-cancer/cancer-types/melanoma/symptoms",
        source_id="cancer-australia",
        source_organization="Cancer Australia",
        title="Melanoma Symptoms - Cancer Australia",
        canonical_cancer_slug="melanoma",
        country_code="AU",
        jurisdiction_scope="COUNTRY",
        publication_status=PublicationStatus.REVIEW_REQUIRED,
        rights_evidence_url="https://www.canceraustralia.gov.au/copyright",
        rights_reviewed_at=None,
        rights_reviewer=None,
        permissible_use="Pending item-level rights audit; subject to Commonwealth of Australia Crown copyright terms",
        redistribution_allowed=False,
        commercial_redistribution_allowed=False,
        full_text_storage_allowed=True,
        derived_summary_allowed=True,
        attribution_required=True,
        attribution_text="Source: Cancer Australia, Australian Government. Licensed under CC BY 4.0.",
        reuse_restrictions="Melanoma skin presentation guides in Australia often incorporate licensed images from Melanoma Institute Australia or clinical colleges.",
        quarantine_reason="Consensus citation; high probability of third-party clinical copyright on dermatological symptoms and illustrations under Commonwealth Crown copyright and CC BY 4.0 conditions.",
        third_party_permission_status="REVIEW_REQUIRED",
    ),
    "https://www.canceraustralia.gov.au/cancer-types/breast-cancer/screening": DocumentRightsDecision(
        url="https://www.canceraustralia.gov.au/cancer-types/breast-cancer/screening",
        source_id="cancer-australia",
        source_organization="Cancer Australia",
        title="BreastScreen Australia Recommendations",
        canonical_cancer_slug="breast-cancer",
        country_code="AU",
        jurisdiction_scope="COUNTRY",
        publication_status=PublicationStatus.REVIEW_REQUIRED,
        rights_evidence_url="https://www.canceraustralia.gov.au/copyright",
        rights_reviewed_at=None,
        rights_reviewer=None,
        permissible_use="Pending item-level rights audit; subject to Commonwealth of Australia Crown copyright terms",
        redistribution_allowed=False,
        commercial_redistribution_allowed=False,
        full_text_storage_allowed=True,
        derived_summary_allowed=True,
        attribution_required=True,
        attribution_text="Source: Cancer Australia, Australian Government. Licensed under CC BY 4.0.",
        reuse_restrictions="BreastScreen Australia is a joint Commonwealth and State/Territory program; guidelines may involve multi-jurisdictional copyright.",
        quarantine_reason="Awaiting exact-document verification of multi-jurisdictional program recommendations under Commonwealth Crown copyright and CC BY 4.0 terms.",
        third_party_permission_status="REVIEW_REQUIRED",
    ),

    # --------------------------------------------------------------------------
    # Centers for Disease Control and Prevention (CDC) - 1 candidate URL
    # Policy: Public domain U.S. Federal Government work with third-party exceptions.
    # Decision: REVIEW_REQUIRED fail-closed; CDC policy specifically identifies exceptions.
    # --------------------------------------------------------------------------
    "https://www.cdc.gov/cancer/colorectal/basic_info/screening/": DocumentRightsDecision(
        url="https://www.cdc.gov/cancer/colorectal/basic_info/screening/",
        source_id="cdc-us",
        source_organization="Centers for Disease Control and Prevention",
        title="Colorectal Cancer Screening Recommendations - CDC",
        canonical_cancer_slug="colorectal-cancer",
        country_code="US",
        jurisdiction_scope="COUNTRY",
        publication_status=PublicationStatus.REVIEW_REQUIRED,
        rights_evidence_url="https://www.cdc.gov/other/agencymaterials.html",
        rights_reviewed_at=None,
        rights_reviewer=None,
        permissible_use="U.S. Federal Government public domain subject to exact-document third-party exception audit",
        redistribution_allowed=False,
        commercial_redistribution_allowed=False,
        full_text_storage_allowed=True,
        derived_summary_allowed=True,
        attribution_required=True,
        attribution_text="Source: Centers for Disease Control and Prevention (CDC).",
        reuse_restrictions="CDC website materials frequently incorporate third-party copyrighted text, clinical flowcharts, or non-public-domain graphics that cannot be freely redistributed.",
        quarantine_reason="Item-level review unresolved. CDC specifically identifies third-party and copyrighted material exceptions on its pages. Without item-level evidence confirming the page contains only public domain text, publication remains fail-closed.",
        third_party_permission_status="REVIEW_REQUIRED",
    ),
}


def get_rights_inventory_entry(url: str) -> Optional[DocumentRightsDecision]:
    """Retrieve rights decision for exact URL."""
    return RIGHTS_INVENTORY.get(url)


def list_rights_inventory() -> List[DocumentRightsDecision]:
    """List all candidate document rights records in deterministic URL order."""
    return [RIGHTS_INVENTORY[url] for url in sorted(RIGHTS_INVENTORY.keys())]


def export_rights_audit_report(db: Optional[Session] = None) -> List[Dict[str, Any]]:
    """
    Generates a deterministic rights audit report for all current candidate documents.
    If a database session is provided, enriches records with linked consensus facts,
    quote snippets, and content record provenance.
    """
    from app.models import ConsensusFactSource, ContentSource, SourceDocument

    report: List[Dict[str, Any]] = []

    for entry in list_rights_inventory():
        item = entry.to_dict()
        item["linked_consensus_citations"] = []
        item["linked_content_records"] = []

        if db:
            doc = db.query(SourceDocument).filter(SourceDocument.original_url == entry.url).first()
            if doc:
                item["source_document_id"] = doc.id
                item["db_publication_status"] = doc.publication_status
                item["db_is_eligible"] = doc.is_publication_eligible()

                # Linked consensus citations
                for cfs in db.query(ConsensusFactSource).filter(ConsensusFactSource.source_document_id == doc.id).all():
                    fact = cfs.fact
                    item["linked_consensus_citations"].append({
                        "fact_key": fact.fact_key,
                        "fact_title": fact.title,
                        "quote_snippet": cfs.quote_snippet,
                        "attribution_text": cfs.attribution_text,
                        "country_code": cfs.country_code,
                    })

                # Linked content records
                for cs in db.query(ContentSource).filter(ContentSource.source_document_id == doc.id).all():
                    rec = cs.content_record
                    item["linked_content_records"].append({
                        "content_record_id": rec.id,
                        "category": rec.category,
                        "quote_snippet": cs.quote_snippet,
                        "attribution_text": cs.attribution_text,
                    })

        report.append(item)

    return report
